import { FormEvent, useMemo, useState } from 'react';
import { ListChecks, Pencil, Plus, RefreshCw, Search, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { useAuth } from '@/contexts/AuthContext';
import { useOperationCenters } from '@/hooks/useCompanies';
import { usePositions } from '@/hooks/useSystemConfig';
import { PinkListEntry, PinkListInput, usePinkList } from '@/hooks/usePinkList';

const MODULE_CODE = 'catalogos_seleccion_lista_rosada';
const today = () => new Date().toISOString().slice(0, 10);
const emptyForm = (): PinkListInput => ({ reference_date: today(), full_name: '', document_number: '', position_id: '', operation_center_id: '', observations: '' });

export default function ListaRosada() {
  const { canCreate, canUpdate, canDelete } = useAuth();
  const { data, isLoading, refetch, create, update, remove, isSaving, isDeleting } = usePinkList();
  const { data: positions = [] } = usePositions();
  const { data: centers = [] } = useOperationCenters();
  const [search, setSearch] = useState(''); const [formOpen, setFormOpen] = useState(false);
  const [editing, setEditing] = useState<PinkListEntry | null>(null); const [form, setForm] = useState<PinkListInput>(emptyForm);
  const [deleteTarget, setDeleteTarget] = useState<PinkListEntry | null>(null);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); return term ? data.filter((item) => [item.full_name, item.document_number, item.positions?.name, item.operation_centers?.name, item.observations].some((value) => value?.toLowerCase().includes(term))) : data; }, [data, search]);
  const openCreate = () => { setEditing(null); setForm(emptyForm()); setFormOpen(true); };
  const openEdit = (item: PinkListEntry) => { setEditing(item); setForm({ reference_date: item.reference_date, full_name: item.full_name, document_number: item.document_number, position_id: item.position_id, operation_center_id: item.operation_center_id, observations: item.observations || '' }); setFormOpen(true); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (editing) await update({ id: editing.id, ...form }); else await create(form); setFormOpen(false); };
  return <div className="selection-catalog-page mx-auto max-w-7xl space-y-6 px-2">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-4"><div className="flex size-14 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ListChecks className="size-7" /></div><div><h1 className="text-2xl font-bold text-foreground">Lista Rosada</h1><p className="text-sm text-muted-foreground">Registro y consulta de personas incluidas en la Lista Rosada.</p></div></div><div className="flex gap-2"><Button variant="outline" size="icon" onClick={() => refetch()} aria-label="Actualizar Lista Rosada"><RefreshCw className={isLoading ? 'size-4 animate-spin' : 'size-4'} /></Button>{canCreate(MODULE_CODE) && <Button onClick={openCreate}><Plus className="mr-2 size-4" />Nuevo registro</Button>}</div></header>
    <div className="rounded-xl border bg-card"><div className="border-b p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="pl-9" placeholder="Buscar por nombre, documento, cargo o centro" /></div></div>{isLoading ? <div className="space-y-3 p-4">{[1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-14 w-full" />)}</div> : filtered.length === 0 ? <div className="py-16 text-center"><ListChecks className="mx-auto mb-3 size-10 text-muted-foreground/40" /><p className="font-medium">No hay registros en Lista Rosada</p><p className="mt-1 text-sm text-muted-foreground">{search ? 'Prueba con otro término de búsqueda.' : 'Crea el primer registro para comenzar.'}</p></div> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Fecha</TableHead><TableHead>Nombre</TableHead><TableHead>Documento</TableHead><TableHead>Cargo</TableHead><TableHead>Centro de operación</TableHead><TableHead>Observaciones</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{filtered.map((item) => <TableRow key={item.id}><TableCell>{item.reference_date}</TableCell><TableCell className="font-medium">{item.full_name}</TableCell><TableCell>{item.document_number}</TableCell><TableCell>{item.positions?.name || '—'}</TableCell><TableCell>{item.operation_centers?.name || '—'}</TableCell><TableCell className="max-w-sm whitespace-normal text-muted-foreground">{item.observations || '—'}</TableCell><TableCell className="text-right"><div className="flex justify-end gap-1">{canUpdate(MODULE_CODE) && <Button variant="ghost" size="icon" onClick={() => openEdit(item)} aria-label={`Editar ${item.full_name}`}><Pencil className="size-4" /></Button>}{canDelete(MODULE_CODE) && <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive" onClick={() => setDeleteTarget(item)} aria-label={`Eliminar ${item.full_name}`}><Trash2 className="size-4" /></Button>}</div></TableCell></TableRow>)}</TableBody></Table></div>}</div>
    <Dialog open={formOpen} onOpenChange={setFormOpen}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{editing ? 'Editar registro de Lista Rosada' : 'Nuevo registro de Lista Rosada'}</DialogTitle><DialogDescription>Completa los datos del registro.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="pink-date">Fecha *</Label><Input id="pink-date" type="date" value={form.reference_date} onChange={(event) => setForm({ ...form, reference_date: event.target.value })} required /></div><div className="space-y-2"><Label htmlFor="pink-document">Documento *</Label><Input id="pink-document" value={form.document_number} onChange={(event) => setForm({ ...form, document_number: event.target.value })} maxLength={50} required /></div></div><div className="space-y-2"><Label htmlFor="pink-name">Nombre *</Label><Input id="pink-name" value={form.full_name} onChange={(event) => setForm({ ...form, full_name: event.target.value })} maxLength={200} required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Cargo *</Label><Select value={form.position_id} onValueChange={(position_id) => setForm({ ...form, position_id })}><SelectTrigger><SelectValue placeholder="Seleccionar cargo" /></SelectTrigger><SelectContent>{positions.map((position) => <SelectItem key={position.id} value={position.id}>{position.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Centro de operación *</Label><Select value={form.operation_center_id} onValueChange={(operation_center_id) => setForm({ ...form, operation_center_id })}><SelectTrigger><SelectValue placeholder="Seleccionar centro" /></SelectTrigger><SelectContent>{centers.map((center) => <SelectItem key={center.id} value={center.id}>{center.name}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label htmlFor="pink-observations">Observaciones</Label><Textarea id="pink-observations" value={form.observations || ''} onChange={(event) => setForm({ ...form, observations: event.target.value })} maxLength={2000} rows={4} /></div><DialogFooter><Button type="button" variant="outline" onClick={() => setFormOpen(false)}>Cancelar</Button><Button type="submit" disabled={isSaving || !form.reference_date || !form.full_name.trim() || !form.document_number.trim() || !form.position_id || !form.operation_center_id}>{isSaving ? 'Guardando…' : editing ? 'Guardar cambios' : 'Crear registro'}</Button></DialogFooter></form></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => !open && setDeleteTarget(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Eliminar registro de Lista Rosada?</AlertDialogTitle><AlertDialogDescription>Se eliminará el registro de {deleteTarget?.full_name}. Esta acción no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={isDeleting} onClick={async () => { if (deleteTarget) { await remove(deleteTarget.id); setDeleteTarget(null); } }}>{isDeleting ? 'Eliminando…' : 'Eliminar'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
