BEGIN;

-- Public leave links are managed through authenticated RPCs and consumed only
-- through the public Edge Function. None of these tables is directly exposed.
CREATE TABLE public.leave_public_access_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  revoked_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  CONSTRAINT leave_public_access_tokens_expiry_check
    CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE UNIQUE INDEX leave_public_access_tokens_one_active_company_idx
  ON public.leave_public_access_tokens (company_id)
  WHERE is_active;

CREATE TABLE public.leave_public_identity_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  access_token_id uuid NOT NULL REFERENCES public.leave_public_access_tokens(id) ON DELETE CASCADE,
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  employee_id uuid NOT NULL REFERENCES public.employees_v2(id) ON DELETE CASCADE,
  session_hash bytea NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_request_id uuid,
  ip_hash bytea NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX leave_public_identity_sessions_expiry_idx
  ON public.leave_public_identity_sessions (expires_at);

CREATE TABLE public.leave_public_access_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  access_token_id uuid NOT NULL REFERENCES public.leave_public_access_tokens(id) ON DELETE CASCADE,
  identity_hash bytea NOT NULL,
  ip_hash bytea NOT NULL,
  success boolean NOT NULL DEFAULT false,
  attempted_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX leave_public_access_attempts_rate_idx
  ON public.leave_public_access_attempts (access_token_id, attempted_at DESC);
CREATE INDEX leave_public_access_attempts_retention_idx
  ON public.leave_public_access_attempts (attempted_at);

ALTER TABLE public.leave_requests
  ADD COLUMN submission_source text NOT NULL DEFAULT 'internal',
  ADD COLUMN public_reference text,
  ADD COLUMN public_access_token_id uuid REFERENCES public.leave_public_access_tokens(id) ON DELETE SET NULL,
  ADD CONSTRAINT leave_requests_submission_source_check
    CHECK (submission_source IN ('internal', 'employee_portal', 'public_link')),
  ADD CONSTRAINT leave_requests_public_origin_check CHECK (
    (submission_source = 'public_link'
      AND created_by IS NULL
      AND public_reference IS NOT NULL
      AND public_access_token_id IS NOT NULL)
    OR
    (submission_source <> 'public_link'
      AND public_reference IS NULL
      AND public_access_token_id IS NULL)
  ),
  ADD CONSTRAINT leave_requests_public_reference_key UNIQUE (public_reference);

ALTER TABLE public.leave_public_identity_sessions
  ADD CONSTRAINT leave_public_identity_sessions_request_fkey
  FOREIGN KEY (created_request_id) REFERENCES public.leave_requests(id) ON DELETE SET NULL;

ALTER TABLE public.leave_public_access_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_public_identity_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_public_access_attempts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.leave_public_access_tokens FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.leave_public_identity_sessions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.leave_public_access_attempts FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.leave_public_access_tokens TO service_role;
GRANT ALL ON TABLE public.leave_public_identity_sessions TO service_role;
GRANT ALL ON TABLE public.leave_public_access_attempts TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.leave_public_access_attempts_id_seq TO service_role;

-- The original documents policy grants company-wide reads by the first path
-- segment. Public leave evidence is more sensitive: it must follow the same
-- request-level and operation-center visibility as the leave request itself.
DROP POLICY IF EXISTS "Users can view company documents" ON storage.objects;
CREATE POLICY "Users can view company documents"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'documents'
  AND NOT (
    coalesce((storage.foldername(name))[2], '') = 'leaves'
    AND coalesce((storage.foldername(name))[3], '') = 'public'
  )
  AND (
    EXISTS (
      SELECT 1 FROM public.user_company_assignments assignment
      WHERE assignment.user_id = (SELECT auth.uid())
        AND assignment.company_id::text = (storage.foldername(name))[1]
    )
    OR public.is_admin()
  )
);

DROP POLICY IF EXISTS "Authorized users can view public leave documents" ON storage.objects;
CREATE POLICY "Authorized users can view public leave documents"
ON storage.objects FOR SELECT TO authenticated
USING (
  bucket_id = 'documents'
  AND coalesce((storage.foldername(name))[2], '') = 'leaves'
  AND coalesce((storage.foldername(name))[3], '') = 'public'
  AND EXISTS (
    SELECT 1
    FROM public.leave_requests request
    WHERE request.document_url = name
      AND request.submission_source = 'public_link'
      AND public.user_can_read_leave_request(
        request.company_id,
        request.employee_id,
        request.created_by,
        request.approval_stage
      )
  )
);

CREATE TRIGGER update_leave_public_access_tokens_updated_at
BEFORE UPDATE ON public.leave_public_access_tokens
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- A dedicated permission keeps link administration separate from ordinary
-- permission-request creation.
WITH parent_module AS (
  SELECT id FROM public.modules WHERE code = 'permisos'
)
INSERT INTO public.modules (code, name, icon, sort_order, parent_id, is_active)
SELECT 'leave_public_links', 'Permisos: Administrar enlace público', 'Link', 803, parent_module.id, true
FROM parent_module
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  sort_order = EXCLUDED.sort_order,
  parent_id = EXCLUDED.parent_id,
  is_active = true;

INSERT INTO public.permissions (module_id, action, description)
SELECT module.id, 'update'::public.permission_action, 'Administrar el enlace público de solicitudes de permisos'
FROM public.modules module
WHERE module.code = 'leave_public_links'
ON CONFLICT (module_id, action) DO UPDATE SET description = EXCLUDED.description;

INSERT INTO public.role_permissions (role_id, permission_id)
SELECT role.id, permission.id
FROM public.custom_roles role
CROSS JOIN public.permissions permission
JOIN public.modules module ON module.id = permission.module_id
WHERE role.is_system
  AND module.code = 'leave_public_links'
ON CONFLICT (role_id, permission_id) DO NOTHING;

CREATE OR REPLACE FUNCTION private.can_manage_leave_public_link(p_company_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT (SELECT auth.uid()) IS NOT NULL
    AND (
      public.is_super_admin()
      OR (
        public.is_company_member(p_company_id)
        AND (
          public.is_admin()
          OR public.check_user_permission((SELECT auth.uid()), 'leave_public_links', 'update')
        )
      )
    );
$$;

REVOKE ALL ON FUNCTION private.can_manage_leave_public_link(uuid) FROM PUBLIC, anon, authenticated, service_role;

CREATE OR REPLACE FUNCTION public.get_leave_public_link_status(p_company_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_token public.leave_public_access_tokens%ROWTYPE;
BEGIN
  IF NOT private.can_manage_leave_public_link(p_company_id) THEN
    RAISE EXCEPTION 'No tienes permiso para administrar el enlace público.' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_token
  FROM public.leave_public_access_tokens token
  WHERE token.company_id = p_company_id AND token.is_active
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('active', false);
  END IF;

  RETURN jsonb_build_object(
    'active', true,
    'id', v_token.id,
    'created_at', v_token.created_at,
    'expires_at', v_token.expires_at,
    'expired', v_token.expires_at IS NOT NULL AND v_token.expires_at <= now()
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.rotate_leave_public_link(
  p_company_id uuid,
  p_expires_at timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_raw_token text := encode(extensions.gen_random_bytes(32), 'hex');
  v_token_id uuid;
BEGIN
  IF NOT private.can_manage_leave_public_link(p_company_id) THEN
    RAISE EXCEPTION 'No tienes permiso para administrar el enlace público.' USING ERRCODE = '42501';
  END IF;
  IF p_expires_at IS NOT NULL AND p_expires_at <= now() THEN
    RAISE EXCEPTION 'La fecha de vencimiento debe estar en el futuro.';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_company_id::text || ':leave-public-link', 0)
  );
  UPDATE public.leave_public_access_tokens
  SET is_active = false, revoked_at = now(), revoked_by = (SELECT auth.uid())
  WHERE company_id = p_company_id AND is_active;
  DELETE FROM public.leave_public_identity_sessions
  WHERE company_id = p_company_id AND used_at IS NULL;
  DELETE FROM public.leave_public_identity_sessions
  WHERE expires_at < now() - interval '7 days';
  DELETE FROM public.leave_public_access_attempts
  WHERE attempted_at < now() - interval '7 days';

  INSERT INTO public.leave_public_access_tokens (
    company_id, token_hash, expires_at, created_by
  ) VALUES (
    p_company_id,
    extensions.digest(v_raw_token, 'sha256'),
    p_expires_at,
    (SELECT auth.uid())
  ) RETURNING id INTO v_token_id;

  RETURN jsonb_build_object(
    'active', true,
    'id', v_token_id,
    'token', v_raw_token,
    'expires_at', p_expires_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_leave_public_link(p_company_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_count integer;
BEGIN
  IF NOT private.can_manage_leave_public_link(p_company_id) THEN
    RAISE EXCEPTION 'No tienes permiso para administrar el enlace público.' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_company_id::text || ':leave-public-link', 0)
  );
  UPDATE public.leave_public_access_tokens
  SET is_active = false, revoked_at = now(), revoked_by = (SELECT auth.uid())
  WHERE company_id = p_company_id AND is_active;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  DELETE FROM public.leave_public_identity_sessions
  WHERE company_id = p_company_id AND used_at IS NULL;
  DELETE FROM public.leave_public_identity_sessions
  WHERE expires_at < now() - interval '7 days';
  DELETE FROM public.leave_public_access_attempts
  WHERE attempted_at < now() - interval '7 days';
  RETURN v_count > 0;
END;
$$;

REVOKE ALL ON FUNCTION public.get_leave_public_link_status(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.rotate_leave_public_link(uuid, timestamptz) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.revoke_leave_public_link(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_leave_public_link_status(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rotate_leave_public_link(uuid, timestamptz) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.revoke_leave_public_link(uuid) TO authenticated, service_role;

-- Shared transactional creator used by the authenticated application and the
-- public service entry point. All derived values are calculated server-side.
CREATE OR REPLACE FUNCTION private.create_leave_request_core(
  p_company_id uuid,
  p_employee_id uuid,
  p_request jsonb,
  p_created_by uuid,
  p_submission_source text,
  p_public_token_id uuid DEFAULT NULL,
  p_document_url text DEFAULT NULL,
  p_document_name text DEFAULT NULL
)
RETURNS public.leave_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_config public.leave_type_config%ROWTYPE;
  v_request public.leave_requests%ROWTYPE;
  v_request_id uuid;
  v_reference text;
  v_leave_type text := nullif(btrim(p_request->>'leave_type'), '');
  v_duration text := coalesce(nullif(btrim(p_request->>'duration_type'), ''), 'dias_completos');
  v_start_date date;
  v_end_date date;
  v_start_time time;
  v_end_time time;
  v_total_days numeric(5,2);
  v_total_hours numeric(5,2);
  v_reason text := nullif(btrim(p_request->>'reason'), '');
  v_used_this_year numeric := 0;
  v_available numeric;
BEGIN
  IF p_submission_source NOT IN ('internal', 'employee_portal', 'public_link') THEN
    RAISE EXCEPTION 'Origen de solicitud inválido.';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.employees_v2 employee
    WHERE employee.id = p_employee_id
      AND employee.company_id = p_company_id
      AND employee.is_active
      AND employee.status = 'active'
      AND EXISTS (
        SELECT 1 FROM public.employee_employment_cycles cycle
        WHERE cycle.employee_id = employee.id
          AND cycle.company_id = employee.company_id
          AND cycle.status = 'active'
      )
  ) THEN
    RAISE EXCEPTION 'El empleado no tiene una vinculación laboral activa.' USING ERRCODE = 'P0001';
  END IF;

  -- Serialize requests for one employee and leave type so concurrent submits
  -- cannot bypass overlap, annual-limit or balance validations.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_employee_id::text || ':' || coalesce(v_leave_type, ''), 0)
  );
  IF v_leave_type IS NULL OR v_reason IS NULL OR char_length(v_reason) < 10 THEN
    RAISE EXCEPTION 'Completa el tipo de permiso y un motivo de al menos 10 caracteres.' USING ERRCODE = '22023';
  END IF;
  IF coalesce(p_request->>'start_date', '') !~ '^\d{4}-\d{2}-\d{2}$'
    OR coalesce(p_request->>'end_date', '') !~ '^\d{4}-\d{2}-\d{2}$' THEN
    RAISE EXCEPTION 'Las fechas de la solicitud no son válidas.' USING ERRCODE = '22023';
  END IF;

  v_start_date := (p_request->>'start_date')::date;
  v_end_date := (p_request->>'end_date')::date;
  IF v_end_date < v_start_date THEN
    RAISE EXCEPTION 'La fecha final no puede ser anterior a la fecha inicial.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_config
  FROM public.leave_type_config config
  WHERE config.company_id = p_company_id
    AND config.leave_type = v_leave_type
    AND config.is_active;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'El tipo de permiso no está disponible.' USING ERRCODE = '22023';
  END IF;
  IF v_start_date < current_date + coalesce(v_config.min_days_advance, 0) THEN
    RAISE EXCEPTION 'La solicitud no cumple la anticipación mínima del tipo de permiso.' USING ERRCODE = '22023';
  END IF;
  IF v_config.requires_document AND nullif(btrim(p_document_url), '') IS NULL THEN
    RAISE EXCEPTION 'Este tipo de permiso requiere un soporte.' USING ERRCODE = '22023';
  END IF;

  IF v_duration = 'dias_completos' THEN
    SELECT count(*)::numeric INTO v_total_days
    FROM generate_series(v_start_date, v_end_date, interval '1 day') day_value
    WHERE extract(dow FROM day_value) <> 0
      AND NOT EXISTS (
        SELECT 1 FROM public.company_holidays holiday
        WHERE holiday.company_id = p_company_id
          AND holiday.holiday_date = day_value::date
          AND holiday.is_active
      );
  ELSIF v_duration = 'medio_dia' THEN
    IF NOT coalesce(v_config.allows_half_day, false) OR v_start_date <> v_end_date THEN
      RAISE EXCEPTION 'Este tipo de permiso no admite medio día o el rango es inválido.' USING ERRCODE = '22023';
    END IF;
    v_total_days := 0.5;
  ELSIF v_duration = 'horas' THEN
    IF NOT coalesce(v_config.allows_hours, false) OR v_start_date <> v_end_date
      OR coalesce(p_request->>'start_time', '') !~ '^\d{2}:\d{2}$'
      OR coalesce(p_request->>'end_time', '') !~ '^\d{2}:\d{2}$' THEN
      RAISE EXCEPTION 'Este tipo de permiso no admite horas o el horario es inválido.' USING ERRCODE = '22023';
    END IF;
    v_start_time := (p_request->>'start_time')::time;
    v_end_time := (p_request->>'end_time')::time;
    v_total_hours := round((extract(epoch FROM (v_end_time - v_start_time)) / 3600.0)::numeric, 2);
    IF v_total_hours <= 0 OR v_total_hours > 8 THEN
      RAISE EXCEPTION 'La duración por horas debe ser mayor que cero y no superar 8 horas.' USING ERRCODE = '22023';
    END IF;
    v_total_days := round(v_total_hours / 8.0, 2);
  ELSE
    RAISE EXCEPTION 'La duración seleccionada no es válida.' USING ERRCODE = '22023';
  END IF;
  IF v_total_days <= 0 THEN
    RAISE EXCEPTION 'El rango seleccionado no contiene días laborables.' USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.vacation_requests request
    WHERE request.employee_id = p_employee_id
      AND request.status <> 'cancelado'
      AND request.start_date <= v_end_date AND request.end_date >= v_start_date
  ) OR EXISTS (
    SELECT 1 FROM public.leave_requests request
    WHERE request.employee_id = p_employee_id
      AND request.status NOT IN ('cancelado', 'rechazado')
      AND request.start_date <= v_end_date AND request.end_date >= v_start_date
  ) OR EXISTS (
    SELECT 1 FROM public.employee_incapacities incapacity
    WHERE incapacity.employee_id = p_employee_id
      AND incapacity.start_date <= v_end_date AND incapacity.end_date >= v_start_date
  ) THEN
    RAISE EXCEPTION 'Las fechas se cruzan con otra ausencia registrada.' USING ERRCODE = '23P01';
  END IF;

  IF v_config.max_days_per_year IS NOT NULL THEN
    SELECT coalesce(sum(request.total_days), 0) INTO v_used_this_year
    FROM public.leave_requests request
    WHERE request.employee_id = p_employee_id
      AND request.leave_type = v_leave_type
      AND extract(year FROM request.start_date) = extract(year FROM v_start_date)
      AND request.status NOT IN ('cancelado', 'rechazado');
    IF v_used_this_year + v_total_days > v_config.max_days_per_year THEN
      RAISE EXCEPTION 'La solicitud supera el máximo anual configurado.' USING ERRCODE = '22023';
    END IF;
  END IF;

  SELECT balance.available_days INTO v_available
  FROM public.leave_balances balance
  WHERE balance.employee_id = p_employee_id
    AND balance.leave_type = v_leave_type
    AND balance.year = extract(year FROM v_start_date)::integer;
  IF FOUND AND v_total_days > v_available THEN
    RAISE EXCEPTION 'La solicitud supera el saldo disponible.' USING ERRCODE = '22023';
  END IF;

  LOOP
    v_request_id := gen_random_uuid();
    v_reference := CASE WHEN p_submission_source = 'public_link'
      THEN 'PER-' || to_char(current_date, 'YYYYMMDD') || '-' || upper(substr(replace(v_request_id::text, '-', ''), 1, 8))
      ELSE NULL
    END;
    EXIT WHEN v_reference IS NULL OR NOT EXISTS (
      SELECT 1 FROM public.leave_requests request WHERE request.public_reference = v_reference
    );
  END LOOP;

  PERFORM set_config('app.leave_workflow_rpc', 'on', true);
  INSERT INTO public.leave_requests (
    id, employee_id, company_id, leave_type, duration_type,
    start_date, end_date, start_time, end_time, total_days, total_hours,
    reason, document_url, document_name, status, approval_stage,
    created_by, submission_source, public_reference, public_access_token_id
  ) VALUES (
    v_request_id, p_employee_id, p_company_id, v_leave_type, v_duration::public.leave_duration_type,
    v_start_date, v_end_date, v_start_time, v_end_time, v_total_days, v_total_hours,
    v_reason, nullif(btrim(p_document_url), ''), nullif(btrim(p_document_name), ''),
    'pendiente', 'pending_manager', p_created_by, p_submission_source,
    v_reference, p_public_token_id
  ) RETURNING * INTO v_request;

  UPDATE public.leave_balances
  SET pending_days = pending_days + v_total_days
  WHERE employee_id = p_employee_id
    AND leave_type = v_leave_type
    AND year = extract(year FROM v_start_date)::integer;

  RETURN v_request;
END;
$$;

REVOKE ALL ON FUNCTION private.create_leave_request_core(uuid, uuid, jsonb, uuid, text, uuid, text, text)
  FROM PUBLIC, anon, authenticated, service_role;

-- All application inserts must pass through the shared creator above. This
-- prevents a privileged client from bypassing the same balance, overlap and
-- policy checks enforced for public submissions.
CREATE OR REPLACE FUNCTION private.enforce_leave_request_creation_workflow()
RETURNS trigger
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF current_setting('app.leave_workflow_rpc', true) = 'on' THEN
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'Las solicitudes de permisos deben crearse mediante el flujo autorizado.'
    USING ERRCODE = '42501';
END;
$$;

REVOKE ALL ON FUNCTION private.enforce_leave_request_creation_workflow()
  FROM PUBLIC, anon, authenticated, service_role;

DROP TRIGGER IF EXISTS enforce_leave_request_creation_workflow ON public.leave_requests;
CREATE TRIGGER enforce_leave_request_creation_workflow
BEFORE INSERT ON public.leave_requests
FOR EACH ROW EXECUTE FUNCTION private.enforce_leave_request_creation_workflow();

CREATE OR REPLACE FUNCTION public.create_leave_request_workflow(p_request jsonb)
RETURNS public.leave_requests
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id uuid := (SELECT auth.uid());
  v_employee_id uuid := nullif(p_request->>'employee_id', '')::uuid;
  v_company_id uuid;
  v_source text;
BEGIN
  IF v_user_id IS NULL OR v_employee_id IS NULL THEN
    RAISE EXCEPTION 'Debes iniciar sesión para crear la solicitud.' USING ERRCODE = '42501';
  END IF;
  SELECT employee.company_id INTO v_company_id
  FROM public.employees_v2 employee WHERE employee.id = v_employee_id;
  IF v_company_id IS NULL THEN
    RAISE EXCEPTION 'Empleado no encontrado.' USING ERRCODE = '22023';
  END IF;
  IF NOT (
    v_employee_id = public.get_my_employee_id()
    OR (
      public.can_access_absence_employee(v_employee_id)
      AND (
        public.is_super_admin() OR public.is_admin_or_rrhh()
        OR public.check_user_permission(v_user_id, 'permisos', 'create')
      )
    )
  ) THEN
    RAISE EXCEPTION 'No tienes permiso para crear esta solicitud.' USING ERRCODE = '42501';
  END IF;
  v_source := CASE WHEN v_employee_id = public.get_my_employee_id() THEN 'employee_portal' ELSE 'internal' END;
  RETURN private.create_leave_request_core(
    v_company_id, v_employee_id, p_request, v_user_id, v_source, NULL,
    p_request->>'document_url', p_request->>'document_name'
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_leave_request_workflow(jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_leave_request_workflow(jsonb) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.resolve_leave_public_context(p_token text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_token public.leave_public_access_tokens%ROWTYPE;
  v_company public.companies%ROWTYPE;
BEGIN
  SELECT * INTO v_token
  FROM public.leave_public_access_tokens token
  WHERE token.token_hash = extensions.digest(coalesce(p_token, ''), 'sha256')
    AND token.is_active
    AND (token.expires_at IS NULL OR token.expires_at > now());
  IF NOT FOUND THEN RETURN jsonb_build_object('valid', false); END IF;
  SELECT * INTO v_company FROM public.companies company WHERE company.id = v_token.company_id;
  RETURN jsonb_build_object(
    'valid', true,
    'token_id', v_token.id,
    'company_id', v_token.company_id,
    'company', jsonb_build_object('name', v_company.name, 'horizontal_logo_url', v_company.horizontal_logo_url)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.identify_leave_public_employee(
  p_token text,
  p_document_type text,
  p_document_number text,
  p_birth_date date,
  p_ip_hash text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_token public.leave_public_access_tokens%ROWTYPE;
  v_employee public.employees_v2%ROWTYPE;
  v_document text := public.normalize_document_number(p_document_number);
  v_identity_hash bytea;
  v_ip_hash bytea;
  v_failed integer;
  v_identity_found boolean;
  v_session text;
  v_types jsonb;
BEGIN
  SELECT * INTO v_token
  FROM public.leave_public_access_tokens token
  WHERE token.token_hash = extensions.digest(coalesce(p_token, ''), 'sha256')
    AND token.is_active
    AND (token.expires_at IS NULL OR token.expires_at > now());
  IF NOT FOUND THEN RETURN jsonb_build_object('success', false, 'code', 'invalid_link'); END IF;

  v_ip_hash := CASE WHEN coalesce(p_ip_hash, '') ~ '^[0-9a-fA-F]{64}$'
    THEN decode(p_ip_hash, 'hex') ELSE extensions.digest('unknown', 'sha256') END;
  v_identity_hash := extensions.digest(
    upper(coalesce(btrim(p_document_type), '')) || ':' || coalesce(v_document, '') || ':' || coalesce(p_birth_date::text, ''),
    'sha256'
  );

  -- Serialize attempts sharing either the IP or normalized identity. Without
  -- both locks, concurrent requests could all observe fewer than five failures
  -- before inserting their own attempt and bypass the fifteen-minute limit.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_token.id::text || ':ip:' || encode(v_ip_hash, 'hex'), 0)
  );
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(v_token.id::text || ':identity:' || encode(v_identity_hash, 'hex'), 0)
  );

  DELETE FROM public.leave_public_identity_sessions
  WHERE expires_at < now() - interval '7 days';
  DELETE FROM public.leave_public_access_attempts
  WHERE attempted_at < now() - interval '7 days';

  SELECT count(*)::integer INTO v_failed
  FROM public.leave_public_access_attempts attempt
  WHERE attempt.access_token_id = v_token.id
    AND NOT attempt.success
    AND attempt.attempted_at > now() - interval '15 minutes'
    AND (attempt.ip_hash = v_ip_hash OR attempt.identity_hash = v_identity_hash);
  IF v_failed >= 5 THEN RETURN jsonb_build_object('success', false, 'code', 'rate_limited'); END IF;

  SELECT * INTO v_employee
  FROM public.employees_v2 employee
  WHERE employee.company_id = v_token.company_id
    AND employee.document_type::text = upper(btrim(coalesce(p_document_type, '')))
    AND public.normalize_document_number(employee.document_number) = v_document
    AND employee.birth_date = p_birth_date
    AND employee.is_active
    AND employee.status = 'active'
    AND EXISTS (
      SELECT 1 FROM public.employee_employment_cycles cycle
      WHERE cycle.employee_id = employee.id
        AND cycle.company_id = employee.company_id
        AND cycle.status = 'active'
    )
  LIMIT 1;

  v_identity_found := FOUND;

  INSERT INTO public.leave_public_access_attempts (access_token_id, identity_hash, ip_hash, success)
  VALUES (v_token.id, v_identity_hash, v_ip_hash, v_identity_found);

  IF NOT v_identity_found THEN
    RETURN jsonb_build_object('success', false, 'code', 'invalid_identity');
  END IF;

  v_session := encode(extensions.gen_random_bytes(32), 'hex');
  INSERT INTO public.leave_public_identity_sessions (
    access_token_id, company_id, employee_id, session_hash, expires_at, ip_hash
  ) VALUES (
    v_token.id, v_token.company_id, v_employee.id,
    extensions.digest(v_session, 'sha256'), now() + interval '10 minutes', v_ip_hash
  );

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'leave_type', config.leave_type,
    'display_name', config.display_name,
    'description', config.description,
    'requires_document', config.requires_document,
    'document_description', config.document_description,
    'min_days_advance', config.min_days_advance,
    'allows_half_day', config.allows_half_day,
    'allows_hours', config.allows_hours,
    'max_days_per_year', config.max_days_per_year
  ) ORDER BY config.display_name), '[]'::jsonb) INTO v_types
  FROM public.leave_type_config config
  WHERE config.company_id = v_token.company_id AND config.is_active;

  RETURN jsonb_build_object(
    'success', true,
    'session', v_session,
    'expires_in_seconds', 600,
    'employee_first_name', v_employee.first_name,
    'leave_types', v_types
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.prepare_leave_public_submission(p_session text)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_session public.leave_public_identity_sessions%ROWTYPE;
  v_reference text;
BEGIN
  SELECT * INTO v_session
  FROM public.leave_public_identity_sessions session
  WHERE session.session_hash = extensions.digest(coalesce(p_session, ''), 'sha256');
  IF NOT FOUND THEN RETURN jsonb_build_object('valid', false); END IF;
  IF v_session.used_at IS NOT NULL AND v_session.created_request_id IS NOT NULL THEN
    SELECT request.public_reference INTO v_reference
    FROM public.leave_requests request WHERE request.id = v_session.created_request_id;
    RETURN jsonb_build_object('valid', true, 'completed', true, 'reference', v_reference);
  END IF;
  IF v_session.expires_at <= now() OR NOT EXISTS (
    SELECT 1 FROM public.leave_public_access_tokens token
    WHERE token.id = v_session.access_token_id AND token.is_active
      AND (token.expires_at IS NULL OR token.expires_at > now())
  ) THEN RETURN jsonb_build_object('valid', false); END IF;
  RETURN jsonb_build_object(
    'valid', true, 'completed', false,
    'company_id', v_session.company_id, 'employee_id', v_session.employee_id
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_leave_public_request(
  p_session text,
  p_request jsonb,
  p_document_url text DEFAULT NULL,
  p_document_name text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_session public.leave_public_identity_sessions%ROWTYPE;
  v_request public.leave_requests%ROWTYPE;
  v_reference text;
BEGIN
  SELECT * INTO v_session
  FROM public.leave_public_identity_sessions session
  WHERE session.session_hash = extensions.digest(coalesce(p_session, ''), 'sha256')
  FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'La sesión de verificación no es válida.' USING ERRCODE = '42501'; END IF;
  IF v_session.used_at IS NOT NULL AND v_session.created_request_id IS NOT NULL THEN
    SELECT request.public_reference INTO v_reference
    FROM public.leave_requests request WHERE request.id = v_session.created_request_id;
    RETURN jsonb_build_object('success', true, 'reference', v_reference, 'idempotent', true);
  END IF;
  IF v_session.expires_at <= now() OR NOT EXISTS (
    SELECT 1 FROM public.leave_public_access_tokens token
    WHERE token.id = v_session.access_token_id AND token.is_active
      AND (token.expires_at IS NULL OR token.expires_at > now())
  ) THEN RAISE EXCEPTION 'La sesión de verificación expiró.' USING ERRCODE = '42501'; END IF;

  v_request := private.create_leave_request_core(
    v_session.company_id, v_session.employee_id, p_request, NULL, 'public_link',
    v_session.access_token_id, p_document_url, p_document_name
  );
  UPDATE public.leave_public_identity_sessions
  SET used_at = now(), created_request_id = v_request.id
  WHERE id = v_session.id;
  RETURN jsonb_build_object('success', true, 'reference', v_request.public_reference, 'idempotent', false);
END;
$$;

REVOKE ALL ON FUNCTION public.resolve_leave_public_context(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.identify_leave_public_employee(text, text, text, date, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.prepare_leave_public_submission(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.submit_leave_public_request(text, jsonb, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_leave_public_context(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.identify_leave_public_employee(text, text, text, date, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.prepare_leave_public_submission(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.submit_leave_public_request(text, jsonb, text, text) TO service_role;

COMMIT;
